apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgC4445G8lFVAA+/oEXalrlj+vCupva+hb+ER9qJmuek9IfZjBrsWBOEJmq1Rw8qri0d0UtpL013DJlSR6cEFr0qtTXAUgLxTGcqvbsq2ITqSnYljBxjoembtQyxY6kndYDuiasRgMbb7RSmyvK2YMh09h/i0He7e5FHTWft8yC6vuLSd+4P24y+ySP6IoGxSbiZsgrbmpuhb65xoDjMbvGm8FTFIiXijwLcKqYQSvZn/PdWR4vgOvZCG3pOYcVqd4NqCECQ5acfDRlOpdY9bHvm6Smv1zmXIzrb0BdgKim7W8iWmTKHmoc/d0CHe13G5Yh9JahEAm1v0KaiYnjJrU+0KfOpDjDzvZLkmNeTa2LxqZgadQ3qGp3Gs2INyZVw27WaAcgiEaTm2vsau2TiBxzj7nTNIDXmaqPXTRwoIlmdlMFT12DqxRjgTWobLHEvUIODxk9A7uD/68HCTnPPhurYfpiG4HZmgHXjP+BrzEr0bAavPzosv+oY/J/NInd023DC0iqEx7anGApePS6FOPm02ZhQNh+fJacPDz3bdVHRFU1uf48GeAkrZBOCFzuyJeSJ6NY5Z/2ompVKYbqY3UiQZOOuDtk7V/AAdyW58Sqp643bxg8hmXyDGcvzRIms7oZL5XstSYo2kwrqKryBMiYUKWguY/7VsYWwAAKihdWZB1o8u3tmjP9DwaH6f3cAKsh4GRKHc9DQVQ==
    DB_USER: AgCPxVZBOoi05pCZH9yGQkiSeLMj4O1Om2bnY5V4BG+ojBekB6edxwmI+tk2EgmnylwcvLZikVcte7DkmDnnL63UCNE8ON4OjWE0Orvn2wZ0aAVx1o7b19NE4iOaAKVKr/7Hly9tYD3l6Z7/i2PgCWu9g9bBCG8+s/+YGDcn8hzRP7Jj5ESLkbZznGlXQxfD4ICwMuf789peLKELJrTq6PZy+A5D4mPFD2JxCeiqy7q06Rx+S+x+a71aaFixNiXsZw5x5gzJl0SGNfkrgtzMnTAFcHjYcmFbqrf2S4/GG902ag1Io9HEApnRWqW5qT4tAsc3a/nAxbUD1Xv5dYPoMQfKcht+BoycD4KsM18y59hMbHFlFbQl9JoKIoqMZSuql5E4Z2+2bHCvNkK/O5/myvtl7V41hkB4qpN6FrvGjLDUtkfEAyec+ESgMFl3vHlnQBGo0BA1HmJIZW4BZBdRBvpbpgc80vZbj5rmDdzsdzP4/GZAWrd7iPTnNjv0i2ZT9KlyhmHMdlxIYuPyY8M+xjvcO4eZtVH7IxzFGhbFabO8jR1QEFizDP8qOHfAg27wEo3w4wY03K2isPz2Drqxd/BekFz6ROro+EeqK0FSRFZY9+9V8WzwBpH0Es/xGVLqFScCeK1VkP9cxsV0SHc79tvvSyspLO9ZWFXfTUuTFh4weF0C2FR1729PjWSu6dH/QtJkCevGJA0PJg==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

